#!/bin/bash

set -e

PID="./tmp/pids/unicorn.pid"
export RAILS_ENV=production
export RACK_ENV=production

echo "Updating gems"
bundle install

echo "Building assets"
bundle exec rake assets:clean assets:precompile

echo "Migrating"
bundle exec rake db:migrate

echo "Stopping app"
test -s "$PID" && kill -QUIT `cat $PID`

echo "Starting app"
bundle exec unicorn -c config/unicorn.rb -E production -D

echo "Done"
